# Generated by Django 4.2 on 2024-02-26 14:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)])),
                ('owner_name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instagram_id', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('voice', models.FileField(upload_to='packages/voices/')),
                ('description', models.TextField()),
                ('price', models.BigIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('instagram_pages', models.ManyToManyField(to='telegram_bot.instagrampage')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('chat_id', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('chat_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('instagram_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_price', models.BigIntegerField()),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('state', models.CharField(choices=[('AC', 'Accepted'), ('RE', 'Rejected'), ('PE', 'Pending')], default='PE', max_length=2)),
                ('links_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='telegram_bot.bankaccount')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='telegram_bot.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='telegram_bot.telegramuser')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='telegram_channels',
            field=models.ManyToManyField(to='telegram_bot.telegramchannel'),
        ),
    ]
